from PyQt5.QtGui import  QFont
H1 = QFont('Inter', 128)
H2 = QFont('Inter', 48)
H3 = QFont('Inter', 32)
button_text = QFont('Inter', 14)
paragraph = QFont('Inter', 14)
paragraphArticle = QFont('Inter', 12)
paragraph_card = QFont('Inter', 10)
radio_button_text = QFont('Inter', 10)